version: '3.4'

services:
  ecommercefrontend:
    image: ${DOCKER_REGISTRY-}ecommercefrontend
    build:
      context: .
      dockerfile: ECommerceFrontEnd/Dockerfile

  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: API/Dockerfile

